//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将新建项设为活动项 的本地化字符串。
        /// </summary>
        public static string autoSelectdNewItem {
            get {
                return ResourceManager.GetString("autoSelectdNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份 的本地化字符串。
        /// </summary>
        public static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本设定 的本地化字符串。
        /// </summary>
        public static string basicSettings {
            get {
                return ResourceManager.GetString("basicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string dataGridColumnCreateTime {
            get {
                return ResourceManager.GetString("dataGridColumnCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string dataGridColumnNote {
            get {
                return ResourceManager.GetString("dataGridColumnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string dataGridColumnOperation {
            get {
                return ResourceManager.GetString("dataGridColumnOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string dataGridColumnSerial {
            get {
                return ResourceManager.GetString("dataGridColumnSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键位 的本地化字符串。
        /// </summary>
        public static string keyBoard {
            get {
                return ResourceManager.GetString("keyBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SL小助手 的本地化字符串。
        /// </summary>
        public static string mainTitle {
            get {
                return ResourceManager.GetString("mainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杂项 的本地化字符串。
        /// </summary>
        public static string misc {
            get {
                return ResourceManager.GetString("misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建项目 的本地化字符串。
        /// </summary>
        public static string newProject {
            get {
                return ResourceManager.GetString("newProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建项目向导 的本地化字符串。
        /// </summary>
        public static string newProjectGuide {
            get {
                return ResourceManager.GetString("newProjectGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目路径 的本地化字符串。
        /// </summary>
        public static string projectPath {
            get {
                return ResourceManager.GetString("projectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目标题 的本地化字符串。
        /// </summary>
        public static string projectTitle {
            get {
                return ResourceManager.GetString("projectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 的本地化字符串。
        /// </summary>
        public static string restore {
            get {
                return ResourceManager.GetString("restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
    }
}
